### PR TITLE
Feat/apache bench

### PR DESCRIPTION
**Pull request by le-anh-dung-05-05**

### CODE REVIEW

**Review by duchuyyyy — COMMENTED** [review]
reformat code chua rua @le-anh-dung-05-05

**Comment by le-anh-dung-05-05** [comment]
I had already refactored @duchuyyyy

**Review by duchuyyyy — APPROVED** [review]

**Comment by duchuyyyy** [comment]
reformat not refactor @le-anh-dung-05-05

**Comment by duchuyyyy** [comment]
reformat with google java format ?   @le-anh-dung-05-05

**Comment by le-anh-dung-05-05** [comment]
Ops! I forgot that

**Pull request merged**
